### ISSUE TITLE
Problem when using Moise

### ISSUE THREAD

**Issue by u473t8** [jacamo-lang/camel-cartago#4]
When using `Moise` and `camel-cartago` separately everything works fine. But when I try to use them together in one project, I have multiple problems with focusing on an artifact. I suppose this happens because somewhere in `camel-cartago` focus operation is overridden to use artifact name as an argument, like `focus(artName)`, and Moise use focus operation with an artifact id as an argument, like `focus(ArtId)`.

**Comment by Sergio-PB** [comment]
I have not yet worked with Moise and the component together.
`camel-cartago` indeed overrides focusing, but calls the next focusing possibility, as for that, the component should not affect Moise's or CArtAgO's focus action, the oposite (Moise or CArtAgO preventing the component methods to work) is possible.

From wich source the `focus` action is not working? Moises's or the component's?

If possible, please attach a screenshot or log with the trace.

**Comment by u473t8** [comment]
Trace changed after upgrading to 0.3 version of the component. But there is still an issue. 
Here is my `jcm` project file:
```
mas exp_mas {

    agent worker {
        roles: worker in org_group
        verbose: 0
    }


    organisation org: org.xml {
        group org_group: org_group {
            responsible-for: org_scheme
            debug: inspector_gui(off)    
        }
        scheme org_scheme: org_scheme
    }

    platform:   jacamo.platform.AgentWebInspector("false")
                     jacamo.platform.EnvironmentWebInspector("false")
                     jacamo.platform.OrganisationWebInspector("false")
                    // artifactComponent.ArtifactCamel("routes.xml --applicationContext.xml")
}
```
Everything works fine when `artifactComponent.ArtifactCamel("routes.xml --applicationContext.xml")` line is commented out. But when it is uncommented something breaks, even if agent code does not contain any camel-cartago artifacts:

```
[ArtifactCamel] Loading route from: routes.xml
[ArtifactCamel] Loading context configurations from: applicationContext.xml
[                          main] DefaultTypeConverter           INFO  Type converters loaded (core: 195, classpath: 1)
[                          main] DefaultCamelContext            INFO  Apache Camel 2.22.2 (CamelContext: routeSQL.xml) is starting
[                          main] ManagedManagementStrategy      INFO  JMX is enabled
[                          main] DefaultCamelContext            INFO  StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[                          main] DefaultCamelContext            INFO  Route: simpleOP started and consuming from: jacamo-artifact://dbArtifact?args=%28%29&operation=retrieve
[                          main] DefaultCamelContext            INFO  Total 1 routes, of which 1 are started
[                          main] DefaultCamelContext            INFO  Apache Camel 2.22.2 (CamelContext: routeSQL.xml) started in 0.381 seconds
[ArtifactCamel] Route successfully loaded and context successfully created.
[jason.infra.centralised.CentralisedAgArch, jacamo.infra.JaCaMoAgArch, jaca.CAgentArch, artifactComponent.CamelArtArch]
[Moise] Workspace org created.
[Moise] scheme created: org_scheme: org_scheme using artifact SchemeBoard
[Moise] group created: org_group: org_group using artifact ora4mas.nopl.GroupBoard
No operation registered: joinWorkspace
joinned workspace orgfocusing on artifact org_group (at workspace org) using namespace defaultNo operation registered: lookupArtifact
focusing on artifact org (at workspace org) using namespace defaultNo operation registered: lookupArtifact
No operation registered: lookupArtifact
No operation registered: lookupArtifact
No operation registered: adoptRole
```

**Comment by u473t8** [comment]
Here is working code for convenience https://github.com/u473t8/mas-playground.git

**Comment by Sergio-PB** [comment]
I believe the issue was fixed with the new version, 0.3.1 .
The problem was on the act method override, which assumed that the artifact was to always be to serve the routes. Now, it check if there is a defined consumer first.

I tried to address your issue before but the given example did not work.

Thank you for noticing this failure.

**Comment by u473t8** [comment]
@Sergio-PB 
I still have a problem. Now agent seems to be able to focus on organization and group artifact but fails to focus on a scheme and adopt a role. And I receive different "No operation registered" messages while successfully completing such operations as for joiWorkspace operation below.

```
[ArtifactCamel] Route successfully loaded and context successfully created.
[jason.infra.centralised.CentralisedAgArch, jacamo.infra.JaCaMoAgArch, jaca.CAgentArch, artifactComponent.CamelArtArch]
[Moise] Workspace org created.
[Moise] scheme created: org_scheme: org_scheme using artifact SchemeBoard
[Moise] group created: org_group: org_group using artifact ora4mas.nopl.GroupBoard
No operation registered: joinWorkspace
joinned workspace orgfocusing on artifact org_group (at workspace org) using namespace defaultNo operation registered: lookupArtifact
focusing on artifact org (at workspace org) using namespace defaultNo operation registered: lookupArtifact
No operation registered: lookupArtifact
No operation registered: lookupArtifact
No operation registered: adoptRole
```
Do you have an example for working both with camel-cartago and moise?
